package com.mlx.uac.model;

import java.util.Date;

public class Passport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passport.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passport.status
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passport.salt
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passport.reg_date
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passport.reg_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passport.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passport.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passport.user_id
     *
     * @return the value of passport.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passport.user_id
     *
     * @param userId the value for passport.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passport.status
     *
     * @return the value of passport.status
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passport.status
     *
     * @param status the value for passport.status
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passport.salt
     *
     * @return the value of passport.salt
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passport.salt
     *
     * @param salt the value for passport.salt
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passport.reg_date
     *
     * @return the value of passport.reg_date
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passport.reg_date
     *
     * @param regDate the value for passport.reg_date
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setRegDate(String regDate) {
        this.regDate = regDate == null ? null : regDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passport.reg_time
     *
     * @return the value of passport.reg_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passport.reg_time
     *
     * @param regTime the value for passport.reg_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setRegTime(String regTime) {
        this.regTime = regTime == null ? null : regTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passport.create_time
     *
     * @return the value of passport.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passport.create_time
     *
     * @param createTime the value for passport.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passport.update_time
     *
     * @return the value of passport.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passport.update_time
     *
     * @param updateTime the value for passport.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}