package com.mlx.uac.model;

import java.util.Date;

public class Token {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token_id
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token_date
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private String tokenDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.status
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token_count
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private Integer tokenCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.access_count
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private Integer accessCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.exp_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private String expTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.bind_type
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private String bindType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.user_bind_id
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private String bindId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.create_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.update_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token_id
     *
     * @return the value of token.token_id
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token_id
     *
     * @param tokenId the value for token.token_id
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token_date
     *
     * @return the value of token.token_date
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public String getTokenDate() {
        return tokenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token_date
     *
     * @param tokenDate the value for token.token_date
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setTokenDate(String tokenDate) {
        this.tokenDate = tokenDate == null ? null : tokenDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.status
     *
     * @return the value of token.status
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.status
     *
     * @param status the value for token.status
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token_count
     *
     * @return the value of token.token_count
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public Integer getTokenCount() {
        return tokenCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token_count
     *
     * @param tokenCount the value for token.token_count
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setTokenCount(Integer tokenCount) {
        this.tokenCount = tokenCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.access_count
     *
     * @return the value of token.access_count
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public Integer getAccessCount() {
        return accessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.access_count
     *
     * @param accessCount the value for token.access_count
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setAccessCount(Integer accessCount) {
        this.accessCount = accessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.exp_time
     *
     * @return the value of token.exp_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public String getExpTime() {
        return expTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.exp_time
     *
     * @param expTime the value for token.exp_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setExpTime(String expTime) {
        this.expTime = expTime == null ? null : expTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.bind_type
     *
     * @return the value of token.bind_type
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public String getBindType() {
        return bindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.bind_type
     *
     * @param bindType the value for token.bind_type
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setBindType(String bindType) {
        this.bindType = bindType == null ? null : bindType.trim();
    }

    public String getBindId() {
		return bindId;
	}

	public void setBindId(String bindId) {
		this.bindId = bindId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.create_time
     *
     * @return the value of token.create_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.create_time
     *
     * @param createTime the value for token.create_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.update_time
     *
     * @return the value of token.update_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.update_time
     *
     * @param updateTime the value for token.update_time
     *
     * @mbggenerated Mon Jun 20 17:09:57 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}