package com.mlx.uac.model;

import java.util.Date;

public class UserSecurityCenter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_security_center.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer userId;
    
    private Integer verifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_security_center.verify_password
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer verifyPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_security_center.verify_mobile
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer verifyMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_security_center.verify_email
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer verifyEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_security_center.verify_card_no
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer verifyCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_security_center.verify_question
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer verifyQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_security_center.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_security_center.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_security_center.user_id
     *
     * @return the value of user_security_center.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_security_center.user_id
     *
     * @param userId the value for user_security_center.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    public Integer getVerifyUserName() {
		return verifyUserName;
	}

	public void setVerifyUserName(Integer verifyUserName) {
		this.verifyUserName = verifyUserName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_security_center.verify_password
     *
     * @return the value of user_security_center.verify_password
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getVerifyPassword() {
        return verifyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_security_center.verify_password
     *
     * @param verifyPassword the value for user_security_center.verify_password
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setVerifyPassword(Integer verifyPassword) {
        this.verifyPassword = verifyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_security_center.verify_mobile
     *
     * @return the value of user_security_center.verify_mobile
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getVerifyMobile() {
        return verifyMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_security_center.verify_mobile
     *
     * @param verifyMobile the value for user_security_center.verify_mobile
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setVerifyMobile(Integer verifyMobile) {
        this.verifyMobile = verifyMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_security_center.verify_email
     *
     * @return the value of user_security_center.verify_email
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getVerifyEmail() {
        return verifyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_security_center.verify_email
     *
     * @param verifyEmail the value for user_security_center.verify_email
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setVerifyEmail(Integer verifyEmail) {
        this.verifyEmail = verifyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_security_center.verify_card_no
     *
     * @return the value of user_security_center.verify_card_no
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getVerifyCardNo() {
        return verifyCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_security_center.verify_card_no
     *
     * @param verifyCardNo the value for user_security_center.verify_card_no
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setVerifyCardNo(Integer verifyCardNo) {
        this.verifyCardNo = verifyCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_security_center.verify_question
     *
     * @return the value of user_security_center.verify_question
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getVerifyQuestion() {
        return verifyQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_security_center.verify_question
     *
     * @param verifyQuestion the value for user_security_center.verify_question
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setVerifyQuestion(Integer verifyQuestion) {
        this.verifyQuestion = verifyQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_security_center.create_time
     *
     * @return the value of user_security_center.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_security_center.create_time
     *
     * @param createTime the value for user_security_center.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_security_center.update_time
     *
     * @return the value of user_security_center.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_security_center.update_time
     *
     * @param updateTime the value for user_security_center.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}