package com.mlx.uac.model;

import java.util.Date;
import java.util.List;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.head_img_url
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.tele_phone
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String telePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.province
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.city
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.district
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.country
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.zip_code
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.card_type
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.card_no
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.buy_count
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer buyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.consume_amount
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Float consumeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.vip
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mark
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.used_mark
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Integer usedMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.reg_date
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.reg_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private String regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    private Date updateTime;
    
    private Passport passport;
    
    private List<UserBindInfo> userBindInfos;
    
    private UserSecurityCenter userSecurityCenter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.head_img_url
     *
     * @return the value of user_info.head_img_url
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.head_img_url
     *
     * @param headImgUrl the value for user_info.head_img_url
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nickname
     *
     * @return the value of user_info.nickname
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nickname
     *
     * @param nickname the value for user_info.nickname
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile
     *
     * @param mobile the value for user_info.mobile
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.tele_phone
     *
     * @return the value of user_info.tele_phone
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getTelePhone() {
        return telePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.tele_phone
     *
     * @param telePhone the value for user_info.tele_phone
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setTelePhone(String telePhone) {
        this.telePhone = telePhone == null ? null : telePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.province
     *
     * @return the value of user_info.province
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.province
     *
     * @param province the value for user_info.province
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.city
     *
     * @return the value of user_info.city
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.city
     *
     * @param city the value for user_info.city
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.district
     *
     * @return the value of user_info.district
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.district
     *
     * @param district the value for user_info.district
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.country
     *
     * @return the value of user_info.country
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.country
     *
     * @param country the value for user_info.country
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.zip_code
     *
     * @return the value of user_info.zip_code
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.zip_code
     *
     * @param zipCode the value for user_info.zip_code
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.card_type
     *
     * @return the value of user_info.card_type
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.card_type
     *
     * @param cardType the value for user_info.card_type
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.card_no
     *
     * @return the value of user_info.card_no
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.card_no
     *
     * @param cardNo the value for user_info.card_no
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.buy_count
     *
     * @return the value of user_info.buy_count
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getBuyCount() {
        return buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.buy_count
     *
     * @param buyCount the value for user_info.buy_count
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setBuyCount(Integer buyCount) {
        this.buyCount = buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.consume_amount
     *
     * @return the value of user_info.consume_amount
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Float getConsumeAmount() {
        return consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.consume_amount
     *
     * @param consumeAmount the value for user_info.consume_amount
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setConsumeAmount(Float consumeAmount) {
        this.consumeAmount = consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.vip
     *
     * @return the value of user_info.vip
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.vip
     *
     * @param vip the value for user_info.vip
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setVip(Integer vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mark
     *
     * @return the value of user_info.mark
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mark
     *
     * @param mark the value for user_info.mark
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.used_mark
     *
     * @return the value of user_info.used_mark
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Integer getUsedMark() {
        return usedMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.used_mark
     *
     * @param usedMark the value for user_info.used_mark
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setUsedMark(Integer usedMark) {
        this.usedMark = usedMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_time
     *
     * @return the value of user_info.last_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_time
     *
     * @param lastTime the value for user_info.last_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.reg_date
     *
     * @return the value of user_info.reg_date
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.reg_date
     *
     * @param regDate the value for user_info.reg_date
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setRegDate(String regDate) {
        this.regDate = regDate == null ? null : regDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.reg_time
     *
     * @return the value of user_info.reg_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public String getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.reg_time
     *
     * @param regTime the value for user_info.reg_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setRegTime(String regTime) {
        this.regTime = regTime == null ? null : regTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbggenerated Wed Jun 15 16:15:37 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public Passport getPassport() {
		return passport;
	}

	public void setPassport(Passport passport) {
		this.passport = passport;
	}

	public List<UserBindInfo> getUserBindInfos() {
		return userBindInfos;
	}

	public void setUserBindInfos(List<UserBindInfo> userBindInfos) {
		this.userBindInfos = userBindInfos;
	}

	public UserSecurityCenter getUserSecurityCenter() {
		return userSecurityCenter;
	}

	public void setUserSecurityCenter(UserSecurityCenter userSecurityCenter) {
		this.userSecurityCenter = userSecurityCenter;
	}
    
}